### ISSUE TITLE
Why is 3.0.3 the recommended Rails version?

### ISSUE THREAD

**Issue by joelmichael** [engineyard/ey-docs#132]
At first I thought it was because 3.1.0 was too new, but then I remembered that the 3.0 branch was up to 3.0.10. So why do your docs on this page recommend an older version of Rails?

And why version 1.0.1 of unicorn when it is presently at version 4.1.1? Amongst others.

http://docs.engineyard.com/appcloud-tech-stack.html

**Comment by janeday** [comment]
We now support Rails 3.1.0 and the Technology Stack page has been updated accordingly. Thanks for your query.

**Comment by danishkhan** [comment]
The reason we have older version of certain technologies is that we first want to spend the time of vetting new versions before you recommend them to our customers. You can easily install newer versions if you like, but those are the ones we have tested and can state that they will be the most stable on EY Cloud.

**Comment by betelgeuse** [comment]
@danishkhan so basically you are saying that to use Engine Yard recommended versions you need to choose between versions with no known security issues and ones that you have been able to test?

**Comment by danishkhan** [comment]
@betelgeuse there is a big difference between security testing and testing how something works with other technologies. We have a technology stack we provide you. We need to test the compatibility of a new version of one technology with all the other technologies we have running for you as well. Just because something doesn't have security issues does not mean it will play nicely with other things.

**Comment by betelgeuse** [comment]
@danishkhan are you aware that 3.0.3 was released almost a year ago?
